version: "3.9"

services:
  sentiment-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sentiment-sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10

  sentiment-api:
    build:
      context: ./SentimentApi
      dockerfile: Dockerfile
    container_name: sentiment-api
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION: "Server=sentiment-sqlserver,1433;Database=SentimentDb;User Id=test_admin;Password=Password123;TrustServerCertificate=True"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
    depends_on:
      sentiment-sqlserver:
        condition: service_healthy
